# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Tue Sep  2 21:53:04 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(756, 515)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setEnabled(True)
        self.groupBox.setMinimumSize(QtCore.QSize(300, 75))
        self.groupBox.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.groupBox.setVisible(False)
        self.groupBox.setObjectName("groupBox")
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(30, 30, 62, 16))
        self.label_4.setMargin(0)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(30, 50, 151, 16))
        self.label_5.setStyleSheet("")
        self.label_5.setObjectName("label_5")
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 30, 16, 16))
        self.label.setStyleSheet("background-color: rgb(255, 155, 103);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 16, 16))
        self.label_2.setStyleSheet("background-color: rgb(168, 255, 171);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(90, 30, 16, 16))
        self.label_3.setStyleSheet("background-color: rgb(255,255, 255);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(110, 30, 71, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(200, 30, 16, 16))
        self.label_8.setAutoFillBackground(True)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtGui.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(220, 30, 71, 16))
        self.label_9.setObjectName("label_9")
        self.horizontalLayout.addWidget(self.groupBox)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.dateEdit = QtGui.QDateEdit(self.centralwidget)
        self.dateEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.dateEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.dateEdit.setDate(QtCore.QDate(2013, 8, 1))
        self.dateEdit.setMinimumDate(QtCore.QDate(1900, 8, 1))
        self.dateEdit.setCurrentSection(QtGui.QDateTimeEdit.MonthSection)
        self.dateEdit.setCalendarPopup(False)
        self.dateEdit.setCurrentSectionIndex(1)
        self.dateEdit.setObjectName("dateEdit")
        self.gridLayout.addWidget(self.dateEdit, 1, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 75))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.first_month_label = QtGui.QLabel(self.centralwidget)
        self.first_month_label.setText("")
        self.first_month_label.setAlignment(QtCore.Qt.AlignCenter)
        self.first_month_label.setObjectName("first_month_label")
        self.verticalLayout_2.addWidget(self.first_month_label)
        self.first_month_table = QtGui.QTableWidget(self.centralwidget)
        self.first_month_table.setMinimumSize(QtCore.QSize(0, 0))
        self.first_month_table.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.first_month_table.setObjectName("first_month_table")
        self.first_month_table.setColumnCount(31)
        self.first_month_table.setRowCount(3)
        item = QtGui.QTableWidgetItem()
        self.first_month_table.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.first_month_table.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.first_month_table.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.first_month_table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.first_month_table.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.first_month_table.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.first_month_table.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.first_month_table.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.first_month_table.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.first_month_table.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.first_month_table.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.first_month_table.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.first_month_table.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.first_month_table.setHorizontalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.first_month_table.setHorizontalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.first_month_table.setHorizontalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.first_month_table.setHorizontalHeaderItem(13, item)
        item = QtGui.QTableWidgetItem()
        self.first_month_table.setHorizontalHeaderItem(14, item)
        item = QtGui.QTableWidgetItem()
        self.first_month_table.setHorizontalHeaderItem(15, item)
        item = QtGui.QTableWidgetItem()
        self.first_month_table.setHorizontalHeaderItem(16, item)
        item = QtGui.QTableWidgetItem()
        self.first_month_table.setHorizontalHeaderItem(17, item)
        item = QtGui.QTableWidgetItem()
        self.first_month_table.setHorizontalHeaderItem(18, item)
        item = QtGui.QTableWidgetItem()
        self.first_month_table.setHorizontalHeaderItem(19, item)
        item = QtGui.QTableWidgetItem()
        self.first_month_table.setHorizontalHeaderItem(20, item)
        item = QtGui.QTableWidgetItem()
        self.first_month_table.setHorizontalHeaderItem(21, item)
        item = QtGui.QTableWidgetItem()
        self.first_month_table.setHorizontalHeaderItem(22, item)
        item = QtGui.QTableWidgetItem()
        self.first_month_table.setHorizontalHeaderItem(23, item)
        item = QtGui.QTableWidgetItem()
        self.first_month_table.setHorizontalHeaderItem(24, item)
        item = QtGui.QTableWidgetItem()
        self.first_month_table.setHorizontalHeaderItem(25, item)
        item = QtGui.QTableWidgetItem()
        self.first_month_table.setHorizontalHeaderItem(26, item)
        item = QtGui.QTableWidgetItem()
        self.first_month_table.setHorizontalHeaderItem(27, item)
        item = QtGui.QTableWidgetItem()
        self.first_month_table.setHorizontalHeaderItem(28, item)
        item = QtGui.QTableWidgetItem()
        self.first_month_table.setHorizontalHeaderItem(29, item)
        item = QtGui.QTableWidgetItem()
        self.first_month_table.setHorizontalHeaderItem(30, item)
        item = QtGui.QTableWidgetItem()
        self.first_month_table.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.first_month_table.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        self.first_month_table.setItem(0, 2, item)
        item = QtGui.QTableWidgetItem()
        self.first_month_table.setItem(0, 3, item)
        item = QtGui.QTableWidgetItem()
        self.first_month_table.setItem(0, 4, item)
        item = QtGui.QTableWidgetItem()
        self.first_month_table.setItem(0, 5, item)
        item = QtGui.QTableWidgetItem()
        self.first_month_table.setItem(0, 6, item)
        item = QtGui.QTableWidgetItem()
        self.first_month_table.setItem(0, 7, item)
        item = QtGui.QTableWidgetItem()
        self.first_month_table.setItem(0, 8, item)
        item = QtGui.QTableWidgetItem()
        self.first_month_table.setItem(0, 9, item)
        item = QtGui.QTableWidgetItem()
        self.first_month_table.setItem(0, 10, item)
        item = QtGui.QTableWidgetItem()
        self.first_month_table.setItem(0, 11, item)
        item = QtGui.QTableWidgetItem()
        self.first_month_table.setItem(0, 12, item)
        item = QtGui.QTableWidgetItem()
        self.first_month_table.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        self.first_month_table.setItem(1, 1, item)
        item = QtGui.QTableWidgetItem()
        self.first_month_table.setItem(1, 2, item)
        item = QtGui.QTableWidgetItem()
        self.first_month_table.setItem(1, 3, item)
        item = QtGui.QTableWidgetItem()
        self.first_month_table.setItem(1, 4, item)
        item = QtGui.QTableWidgetItem()
        self.first_month_table.setItem(1, 5, item)
        item = QtGui.QTableWidgetItem()
        self.first_month_table.setItem(1, 6, item)
        item = QtGui.QTableWidgetItem()
        self.first_month_table.setItem(1, 7, item)
        item = QtGui.QTableWidgetItem()
        self.first_month_table.setItem(1, 8, item)
        item = QtGui.QTableWidgetItem()
        self.first_month_table.setItem(1, 9, item)
        item = QtGui.QTableWidgetItem()
        self.first_month_table.setItem(1, 10, item)
        item = QtGui.QTableWidgetItem()
        self.first_month_table.setItem(1, 11, item)
        item = QtGui.QTableWidgetItem()
        self.first_month_table.setItem(1, 12, item)
        item = QtGui.QTableWidgetItem()
        self.first_month_table.setItem(1, 13, item)
        item = QtGui.QTableWidgetItem()
        self.first_month_table.setItem(1, 14, item)
        item = QtGui.QTableWidgetItem()
        self.first_month_table.setItem(1, 15, item)
        item = QtGui.QTableWidgetItem()
        self.first_month_table.setItem(1, 16, item)
        item = QtGui.QTableWidgetItem()
        self.first_month_table.setItem(1, 17, item)
        item = QtGui.QTableWidgetItem()
        self.first_month_table.setItem(1, 18, item)
        item = QtGui.QTableWidgetItem()
        self.first_month_table.setItem(1, 19, item)
        item = QtGui.QTableWidgetItem()
        self.first_month_table.setItem(1, 20, item)
        item = QtGui.QTableWidgetItem()
        self.first_month_table.setItem(1, 21, item)
        item = QtGui.QTableWidgetItem()
        self.first_month_table.setItem(1, 22, item)
        item = QtGui.QTableWidgetItem()
        self.first_month_table.setItem(1, 23, item)
        item = QtGui.QTableWidgetItem()
        self.first_month_table.setItem(1, 24, item)
        item = QtGui.QTableWidgetItem()
        self.first_month_table.setItem(1, 25, item)
        item = QtGui.QTableWidgetItem()
        self.first_month_table.setItem(1, 26, item)
        item = QtGui.QTableWidgetItem()
        self.first_month_table.setItem(1, 27, item)
        item = QtGui.QTableWidgetItem()
        self.first_month_table.setItem(1, 28, item)
        item = QtGui.QTableWidgetItem()
        self.first_month_table.setItem(1, 29, item)
        item = QtGui.QTableWidgetItem()
        self.first_month_table.setItem(1, 30, item)
        self.first_month_table.horizontalHeader().setDefaultSectionSize(22)
        self.first_month_table.horizontalHeader().setMinimumSectionSize(5)
        self.first_month_table.verticalHeader().setDefaultSectionSize(22)
        self.first_month_table.verticalHeader().setMinimumSectionSize(5)
        self.verticalLayout_2.addWidget(self.first_month_table)
        self.second_month_label = QtGui.QLabel(self.centralwidget)
        self.second_month_label.setText("")
        self.second_month_label.setAlignment(QtCore.Qt.AlignCenter)
        self.second_month_label.setObjectName("second_month_label")
        self.verticalLayout_2.addWidget(self.second_month_label)
        self.second_month_table = QtGui.QTableWidget(self.centralwidget)
        self.second_month_table.setMinimumSize(QtCore.QSize(0, 0))
        self.second_month_table.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.second_month_table.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.second_month_table.setObjectName("second_month_table")
        self.second_month_table.setColumnCount(31)
        self.second_month_table.setRowCount(3)
        item = QtGui.QTableWidgetItem()
        self.second_month_table.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.second_month_table.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.second_month_table.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.second_month_table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.second_month_table.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.second_month_table.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.second_month_table.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.second_month_table.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.second_month_table.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.second_month_table.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.second_month_table.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.second_month_table.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.second_month_table.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.second_month_table.setHorizontalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.second_month_table.setHorizontalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.second_month_table.setHorizontalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.second_month_table.setHorizontalHeaderItem(13, item)
        item = QtGui.QTableWidgetItem()
        self.second_month_table.setHorizontalHeaderItem(14, item)
        item = QtGui.QTableWidgetItem()
        self.second_month_table.setHorizontalHeaderItem(15, item)
        item = QtGui.QTableWidgetItem()
        self.second_month_table.setHorizontalHeaderItem(16, item)
        item = QtGui.QTableWidgetItem()
        self.second_month_table.setHorizontalHeaderItem(17, item)
        item = QtGui.QTableWidgetItem()
        self.second_month_table.setHorizontalHeaderItem(18, item)
        item = QtGui.QTableWidgetItem()
        self.second_month_table.setHorizontalHeaderItem(19, item)
        item = QtGui.QTableWidgetItem()
        self.second_month_table.setHorizontalHeaderItem(20, item)
        item = QtGui.QTableWidgetItem()
        self.second_month_table.setHorizontalHeaderItem(21, item)
        item = QtGui.QTableWidgetItem()
        self.second_month_table.setHorizontalHeaderItem(22, item)
        item = QtGui.QTableWidgetItem()
        self.second_month_table.setHorizontalHeaderItem(23, item)
        item = QtGui.QTableWidgetItem()
        self.second_month_table.setHorizontalHeaderItem(24, item)
        item = QtGui.QTableWidgetItem()
        self.second_month_table.setHorizontalHeaderItem(25, item)
        item = QtGui.QTableWidgetItem()
        self.second_month_table.setHorizontalHeaderItem(26, item)
        item = QtGui.QTableWidgetItem()
        self.second_month_table.setHorizontalHeaderItem(27, item)
        item = QtGui.QTableWidgetItem()
        self.second_month_table.setHorizontalHeaderItem(28, item)
        item = QtGui.QTableWidgetItem()
        self.second_month_table.setHorizontalHeaderItem(29, item)
        item = QtGui.QTableWidgetItem()
        self.second_month_table.setHorizontalHeaderItem(30, item)
        item = QtGui.QTableWidgetItem()
        self.second_month_table.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.second_month_table.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        self.second_month_table.setItem(0, 2, item)
        item = QtGui.QTableWidgetItem()
        self.second_month_table.setItem(0, 3, item)
        item = QtGui.QTableWidgetItem()
        self.second_month_table.setItem(0, 4, item)
        item = QtGui.QTableWidgetItem()
        self.second_month_table.setItem(0, 5, item)
        item = QtGui.QTableWidgetItem()
        self.second_month_table.setItem(0, 6, item)
        item = QtGui.QTableWidgetItem()
        self.second_month_table.setItem(0, 7, item)
        item = QtGui.QTableWidgetItem()
        self.second_month_table.setItem(0, 8, item)
        item = QtGui.QTableWidgetItem()
        self.second_month_table.setItem(0, 9, item)
        item = QtGui.QTableWidgetItem()
        self.second_month_table.setItem(0, 10, item)
        item = QtGui.QTableWidgetItem()
        self.second_month_table.setItem(0, 11, item)
        item = QtGui.QTableWidgetItem()
        self.second_month_table.setItem(0, 12, item)
        item = QtGui.QTableWidgetItem()
        self.second_month_table.setItem(0, 13, item)
        item = QtGui.QTableWidgetItem()
        self.second_month_table.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        self.second_month_table.setItem(1, 1, item)
        item = QtGui.QTableWidgetItem()
        self.second_month_table.setItem(1, 2, item)
        item = QtGui.QTableWidgetItem()
        self.second_month_table.setItem(1, 3, item)
        item = QtGui.QTableWidgetItem()
        self.second_month_table.setItem(1, 4, item)
        item = QtGui.QTableWidgetItem()
        self.second_month_table.setItem(1, 5, item)
        item = QtGui.QTableWidgetItem()
        self.second_month_table.setItem(1, 6, item)
        item = QtGui.QTableWidgetItem()
        self.second_month_table.setItem(1, 7, item)
        item = QtGui.QTableWidgetItem()
        self.second_month_table.setItem(1, 8, item)
        item = QtGui.QTableWidgetItem()
        self.second_month_table.setItem(1, 9, item)
        item = QtGui.QTableWidgetItem()
        self.second_month_table.setItem(1, 10, item)
        item = QtGui.QTableWidgetItem()
        self.second_month_table.setItem(1, 11, item)
        item = QtGui.QTableWidgetItem()
        self.second_month_table.setItem(1, 12, item)
        item = QtGui.QTableWidgetItem()
        self.second_month_table.setItem(1, 13, item)
        item = QtGui.QTableWidgetItem()
        self.second_month_table.setItem(1, 14, item)
        item = QtGui.QTableWidgetItem()
        self.second_month_table.setItem(1, 15, item)
        item = QtGui.QTableWidgetItem()
        self.second_month_table.setItem(1, 16, item)
        item = QtGui.QTableWidgetItem()
        self.second_month_table.setItem(1, 17, item)
        item = QtGui.QTableWidgetItem()
        self.second_month_table.setItem(1, 18, item)
        item = QtGui.QTableWidgetItem()
        self.second_month_table.setItem(1, 19, item)
        item = QtGui.QTableWidgetItem()
        self.second_month_table.setItem(1, 20, item)
        item = QtGui.QTableWidgetItem()
        self.second_month_table.setItem(1, 21, item)
        self.second_month_table.horizontalHeader().setDefaultSectionSize(22)
        self.second_month_table.horizontalHeader().setMinimumSectionSize(5)
        self.second_month_table.verticalHeader().setDefaultSectionSize(22)
        self.second_month_table.verticalHeader().setMinimumSectionSize(5)
        self.verticalLayout_2.addWidget(self.second_month_table)
        self.third_month_label = QtGui.QLabel(self.centralwidget)
        self.third_month_label.setText("")
        self.third_month_label.setAlignment(QtCore.Qt.AlignCenter)
        self.third_month_label.setObjectName("third_month_label")
        self.verticalLayout_2.addWidget(self.third_month_label)
        self.third_month_table = QtGui.QTableWidget(self.centralwidget)
        self.third_month_table.setMinimumSize(QtCore.QSize(0, 0))
        self.third_month_table.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.third_month_table.setObjectName("third_month_table")
        self.third_month_table.setColumnCount(31)
        self.third_month_table.setRowCount(3)
        item = QtGui.QTableWidgetItem()
        self.third_month_table.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.third_month_table.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.third_month_table.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.third_month_table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.third_month_table.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.third_month_table.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.third_month_table.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.third_month_table.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.third_month_table.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.third_month_table.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.third_month_table.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.third_month_table.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.third_month_table.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.third_month_table.setHorizontalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.third_month_table.setHorizontalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.third_month_table.setHorizontalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.third_month_table.setHorizontalHeaderItem(13, item)
        item = QtGui.QTableWidgetItem()
        self.third_month_table.setHorizontalHeaderItem(14, item)
        item = QtGui.QTableWidgetItem()
        self.third_month_table.setHorizontalHeaderItem(15, item)
        item = QtGui.QTableWidgetItem()
        self.third_month_table.setHorizontalHeaderItem(16, item)
        item = QtGui.QTableWidgetItem()
        self.third_month_table.setHorizontalHeaderItem(17, item)
        item = QtGui.QTableWidgetItem()
        self.third_month_table.setHorizontalHeaderItem(18, item)
        item = QtGui.QTableWidgetItem()
        self.third_month_table.setHorizontalHeaderItem(19, item)
        item = QtGui.QTableWidgetItem()
        self.third_month_table.setHorizontalHeaderItem(20, item)
        item = QtGui.QTableWidgetItem()
        self.third_month_table.setHorizontalHeaderItem(21, item)
        item = QtGui.QTableWidgetItem()
        self.third_month_table.setHorizontalHeaderItem(22, item)
        item = QtGui.QTableWidgetItem()
        self.third_month_table.setHorizontalHeaderItem(23, item)
        item = QtGui.QTableWidgetItem()
        self.third_month_table.setHorizontalHeaderItem(24, item)
        item = QtGui.QTableWidgetItem()
        self.third_month_table.setHorizontalHeaderItem(25, item)
        item = QtGui.QTableWidgetItem()
        self.third_month_table.setHorizontalHeaderItem(26, item)
        item = QtGui.QTableWidgetItem()
        self.third_month_table.setHorizontalHeaderItem(27, item)
        item = QtGui.QTableWidgetItem()
        self.third_month_table.setHorizontalHeaderItem(28, item)
        item = QtGui.QTableWidgetItem()
        self.third_month_table.setHorizontalHeaderItem(29, item)
        item = QtGui.QTableWidgetItem()
        self.third_month_table.setHorizontalHeaderItem(30, item)
        item = QtGui.QTableWidgetItem()
        self.third_month_table.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.third_month_table.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        self.third_month_table.setItem(0, 2, item)
        item = QtGui.QTableWidgetItem()
        self.third_month_table.setItem(0, 3, item)
        item = QtGui.QTableWidgetItem()
        self.third_month_table.setItem(0, 4, item)
        item = QtGui.QTableWidgetItem()
        self.third_month_table.setItem(0, 5, item)
        item = QtGui.QTableWidgetItem()
        self.third_month_table.setItem(0, 6, item)
        item = QtGui.QTableWidgetItem()
        self.third_month_table.setItem(0, 7, item)
        item = QtGui.QTableWidgetItem()
        self.third_month_table.setItem(0, 8, item)
        item = QtGui.QTableWidgetItem()
        self.third_month_table.setItem(0, 9, item)
        item = QtGui.QTableWidgetItem()
        self.third_month_table.setItem(0, 10, item)
        item = QtGui.QTableWidgetItem()
        self.third_month_table.setItem(0, 11, item)
        item = QtGui.QTableWidgetItem()
        self.third_month_table.setItem(0, 12, item)
        item = QtGui.QTableWidgetItem()
        self.third_month_table.setItem(0, 13, item)
        item = QtGui.QTableWidgetItem()
        self.third_month_table.setItem(0, 14, item)
        item = QtGui.QTableWidgetItem()
        self.third_month_table.setItem(0, 15, item)
        item = QtGui.QTableWidgetItem()
        self.third_month_table.setItem(0, 16, item)
        item = QtGui.QTableWidgetItem()
        self.third_month_table.setItem(0, 17, item)
        item = QtGui.QTableWidgetItem()
        self.third_month_table.setItem(0, 18, item)
        item = QtGui.QTableWidgetItem()
        self.third_month_table.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        self.third_month_table.setItem(1, 1, item)
        item = QtGui.QTableWidgetItem()
        self.third_month_table.setItem(1, 2, item)
        item = QtGui.QTableWidgetItem()
        self.third_month_table.setItem(1, 3, item)
        item = QtGui.QTableWidgetItem()
        self.third_month_table.setItem(1, 4, item)
        item = QtGui.QTableWidgetItem()
        self.third_month_table.setItem(1, 5, item)
        item = QtGui.QTableWidgetItem()
        self.third_month_table.setItem(1, 6, item)
        item = QtGui.QTableWidgetItem()
        self.third_month_table.setItem(1, 7, item)
        item = QtGui.QTableWidgetItem()
        self.third_month_table.setItem(1, 8, item)
        item = QtGui.QTableWidgetItem()
        self.third_month_table.setItem(1, 9, item)
        item = QtGui.QTableWidgetItem()
        self.third_month_table.setItem(1, 10, item)
        item = QtGui.QTableWidgetItem()
        self.third_month_table.setItem(1, 11, item)
        item = QtGui.QTableWidgetItem()
        self.third_month_table.setItem(1, 12, item)
        item = QtGui.QTableWidgetItem()
        self.third_month_table.setItem(1, 13, item)
        item = QtGui.QTableWidgetItem()
        self.third_month_table.setItem(1, 14, item)
        item = QtGui.QTableWidgetItem()
        self.third_month_table.setItem(1, 15, item)
        item = QtGui.QTableWidgetItem()
        self.third_month_table.setItem(1, 16, item)
        item = QtGui.QTableWidgetItem()
        self.third_month_table.setItem(1, 17, item)
        item = QtGui.QTableWidgetItem()
        self.third_month_table.setItem(1, 18, item)
        item = QtGui.QTableWidgetItem()
        self.third_month_table.setItem(1, 19, item)
        item = QtGui.QTableWidgetItem()
        self.third_month_table.setItem(1, 20, item)
        item = QtGui.QTableWidgetItem()
        self.third_month_table.setItem(1, 21, item)
        self.third_month_table.horizontalHeader().setDefaultSectionSize(22)
        self.third_month_table.horizontalHeader().setMinimumSectionSize(5)
        self.third_month_table.verticalHeader().setDefaultSectionSize(22)
        self.third_month_table.verticalHeader().setMinimumSectionSize(5)
        self.verticalLayout_2.addWidget(self.third_month_table)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar()
        self.menubar.setGeometry(QtCore.QRect(0, 0, 756, 22))
        self.menubar.setObjectName("menubar")
        self.fileMenu = QtGui.QMenu(self.menubar)
        self.fileMenu.setObjectName("fileMenu")
        self.helpMenu = QtGui.QMenu(self.menubar)
        self.helpMenu.setObjectName("helpMenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionLoad = QtGui.QAction(MainWindow)
        self.actionLoad.setObjectName("actionLoad")
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionHelp = QtGui.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionExport = QtGui.QAction(MainWindow)
        self.actionExport.setObjectName("actionExport")
        self.fileMenu.addAction(self.actionSave)
        self.fileMenu.addAction(self.actionLoad)
        self.fileMenu.addSeparator()
        self.fileMenu.addAction(self.actionExport)
        self.fileMenu.addSeparator()
        self.fileMenu.addAction(self.actionQuit)
        self.helpMenu.addAction(self.actionHelp)
        self.helpMenu.addSeparator()
        self.helpMenu.addAction(self.actionAbout)
        self.menubar.addAction(self.fileMenu.menuAction())
        self.menubar.addAction(self.helpMenu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL("clicked()"), self.groupBox.show)
        QtCore.QObject.connect(self.actionQuit, QtCore.SIGNAL("triggered()"), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.pushButton, self.dateEdit)
        MainWindow.setTabOrder(self.dateEdit, self.first_month_table)
        MainWindow.setTabOrder(self.first_month_table, self.second_month_table)
        MainWindow.setTabOrder(self.second_month_table, self.third_month_table)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Womanager", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Legend", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Friday", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "3rd week free weekday", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "free day", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "workday", None, QtGui.QApplication.UnicodeUTF8))
        self.dateEdit.setDisplayFormat(QtGui.QApplication.translate("MainWindow", "yyyy.MM.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "first month:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("MainWindow", "Manage!", None, QtGui.QApplication.UnicodeUTF8))
        self.first_month_table.verticalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Jack", None, QtGui.QApplication.UnicodeUTF8))
        self.first_month_table.verticalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Jane", None, QtGui.QApplication.UnicodeUTF8))
        self.first_month_table.verticalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "Joe", None, QtGui.QApplication.UnicodeUTF8))
        self.first_month_table.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.first_month_table.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.first_month_table.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.first_month_table.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.first_month_table.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.first_month_table.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("MainWindow", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.first_month_table.horizontalHeaderItem(6).setText(QtGui.QApplication.translate("MainWindow", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.first_month_table.horizontalHeaderItem(7).setText(QtGui.QApplication.translate("MainWindow", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.first_month_table.horizontalHeaderItem(8).setText(QtGui.QApplication.translate("MainWindow", "9", None, QtGui.QApplication.UnicodeUTF8))
        self.first_month_table.horizontalHeaderItem(9).setText(QtGui.QApplication.translate("MainWindow", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.first_month_table.horizontalHeaderItem(10).setText(QtGui.QApplication.translate("MainWindow", "11", None, QtGui.QApplication.UnicodeUTF8))
        self.first_month_table.horizontalHeaderItem(11).setText(QtGui.QApplication.translate("MainWindow", "12", None, QtGui.QApplication.UnicodeUTF8))
        self.first_month_table.horizontalHeaderItem(12).setText(QtGui.QApplication.translate("MainWindow", "13", None, QtGui.QApplication.UnicodeUTF8))
        self.first_month_table.horizontalHeaderItem(13).setText(QtGui.QApplication.translate("MainWindow", "14", None, QtGui.QApplication.UnicodeUTF8))
        self.first_month_table.horizontalHeaderItem(14).setText(QtGui.QApplication.translate("MainWindow", "15", None, QtGui.QApplication.UnicodeUTF8))
        self.first_month_table.horizontalHeaderItem(15).setText(QtGui.QApplication.translate("MainWindow", "16", None, QtGui.QApplication.UnicodeUTF8))
        self.first_month_table.horizontalHeaderItem(16).setText(QtGui.QApplication.translate("MainWindow", "17", None, QtGui.QApplication.UnicodeUTF8))
        self.first_month_table.horizontalHeaderItem(17).setText(QtGui.QApplication.translate("MainWindow", "18", None, QtGui.QApplication.UnicodeUTF8))
        self.first_month_table.horizontalHeaderItem(18).setText(QtGui.QApplication.translate("MainWindow", "19", None, QtGui.QApplication.UnicodeUTF8))
        self.first_month_table.horizontalHeaderItem(19).setText(QtGui.QApplication.translate("MainWindow", "20", None, QtGui.QApplication.UnicodeUTF8))
        self.first_month_table.horizontalHeaderItem(20).setText(QtGui.QApplication.translate("MainWindow", "21", None, QtGui.QApplication.UnicodeUTF8))
        self.first_month_table.horizontalHeaderItem(21).setText(QtGui.QApplication.translate("MainWindow", "22", None, QtGui.QApplication.UnicodeUTF8))
        self.first_month_table.horizontalHeaderItem(22).setText(QtGui.QApplication.translate("MainWindow", "23", None, QtGui.QApplication.UnicodeUTF8))
        self.first_month_table.horizontalHeaderItem(23).setText(QtGui.QApplication.translate("MainWindow", "24", None, QtGui.QApplication.UnicodeUTF8))
        self.first_month_table.horizontalHeaderItem(24).setText(QtGui.QApplication.translate("MainWindow", "25", None, QtGui.QApplication.UnicodeUTF8))
        self.first_month_table.horizontalHeaderItem(25).setText(QtGui.QApplication.translate("MainWindow", "26", None, QtGui.QApplication.UnicodeUTF8))
        self.first_month_table.horizontalHeaderItem(26).setText(QtGui.QApplication.translate("MainWindow", "27", None, QtGui.QApplication.UnicodeUTF8))
        self.first_month_table.horizontalHeaderItem(27).setText(QtGui.QApplication.translate("MainWindow", "28", None, QtGui.QApplication.UnicodeUTF8))
        self.first_month_table.horizontalHeaderItem(28).setText(QtGui.QApplication.translate("MainWindow", "29", None, QtGui.QApplication.UnicodeUTF8))
        self.first_month_table.horizontalHeaderItem(29).setText(QtGui.QApplication.translate("MainWindow", "30", None, QtGui.QApplication.UnicodeUTF8))
        self.first_month_table.horizontalHeaderItem(30).setText(QtGui.QApplication.translate("MainWindow", "31", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.first_month_table.isSortingEnabled()
        self.first_month_table.setSortingEnabled(False)
        self.first_month_table.setSortingEnabled(__sortingEnabled)
        self.second_month_table.verticalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Jack", None, QtGui.QApplication.UnicodeUTF8))
        self.second_month_table.verticalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Jane", None, QtGui.QApplication.UnicodeUTF8))
        self.second_month_table.verticalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "Joe", None, QtGui.QApplication.UnicodeUTF8))
        self.second_month_table.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.second_month_table.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.second_month_table.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.second_month_table.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.second_month_table.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.second_month_table.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("MainWindow", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.second_month_table.horizontalHeaderItem(6).setText(QtGui.QApplication.translate("MainWindow", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.second_month_table.horizontalHeaderItem(7).setText(QtGui.QApplication.translate("MainWindow", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.second_month_table.horizontalHeaderItem(8).setText(QtGui.QApplication.translate("MainWindow", "9", None, QtGui.QApplication.UnicodeUTF8))
        self.second_month_table.horizontalHeaderItem(9).setText(QtGui.QApplication.translate("MainWindow", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.second_month_table.horizontalHeaderItem(10).setText(QtGui.QApplication.translate("MainWindow", "11", None, QtGui.QApplication.UnicodeUTF8))
        self.second_month_table.horizontalHeaderItem(11).setText(QtGui.QApplication.translate("MainWindow", "12", None, QtGui.QApplication.UnicodeUTF8))
        self.second_month_table.horizontalHeaderItem(12).setText(QtGui.QApplication.translate("MainWindow", "13", None, QtGui.QApplication.UnicodeUTF8))
        self.second_month_table.horizontalHeaderItem(13).setText(QtGui.QApplication.translate("MainWindow", "14", None, QtGui.QApplication.UnicodeUTF8))
        self.second_month_table.horizontalHeaderItem(14).setText(QtGui.QApplication.translate("MainWindow", "15", None, QtGui.QApplication.UnicodeUTF8))
        self.second_month_table.horizontalHeaderItem(15).setText(QtGui.QApplication.translate("MainWindow", "16", None, QtGui.QApplication.UnicodeUTF8))
        self.second_month_table.horizontalHeaderItem(16).setText(QtGui.QApplication.translate("MainWindow", "17", None, QtGui.QApplication.UnicodeUTF8))
        self.second_month_table.horizontalHeaderItem(17).setText(QtGui.QApplication.translate("MainWindow", "18", None, QtGui.QApplication.UnicodeUTF8))
        self.second_month_table.horizontalHeaderItem(18).setText(QtGui.QApplication.translate("MainWindow", "19", None, QtGui.QApplication.UnicodeUTF8))
        self.second_month_table.horizontalHeaderItem(19).setText(QtGui.QApplication.translate("MainWindow", "20", None, QtGui.QApplication.UnicodeUTF8))
        self.second_month_table.horizontalHeaderItem(20).setText(QtGui.QApplication.translate("MainWindow", "21", None, QtGui.QApplication.UnicodeUTF8))
        self.second_month_table.horizontalHeaderItem(21).setText(QtGui.QApplication.translate("MainWindow", "22", None, QtGui.QApplication.UnicodeUTF8))
        self.second_month_table.horizontalHeaderItem(22).setText(QtGui.QApplication.translate("MainWindow", "23", None, QtGui.QApplication.UnicodeUTF8))
        self.second_month_table.horizontalHeaderItem(23).setText(QtGui.QApplication.translate("MainWindow", "24", None, QtGui.QApplication.UnicodeUTF8))
        self.second_month_table.horizontalHeaderItem(24).setText(QtGui.QApplication.translate("MainWindow", "25", None, QtGui.QApplication.UnicodeUTF8))
        self.second_month_table.horizontalHeaderItem(25).setText(QtGui.QApplication.translate("MainWindow", "26", None, QtGui.QApplication.UnicodeUTF8))
        self.second_month_table.horizontalHeaderItem(26).setText(QtGui.QApplication.translate("MainWindow", "27", None, QtGui.QApplication.UnicodeUTF8))
        self.second_month_table.horizontalHeaderItem(27).setText(QtGui.QApplication.translate("MainWindow", "28", None, QtGui.QApplication.UnicodeUTF8))
        self.second_month_table.horizontalHeaderItem(28).setText(QtGui.QApplication.translate("MainWindow", "29", None, QtGui.QApplication.UnicodeUTF8))
        self.second_month_table.horizontalHeaderItem(29).setText(QtGui.QApplication.translate("MainWindow", "30", None, QtGui.QApplication.UnicodeUTF8))
        self.second_month_table.horizontalHeaderItem(30).setText(QtGui.QApplication.translate("MainWindow", "31", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.second_month_table.isSortingEnabled()
        self.second_month_table.setSortingEnabled(False)
        self.second_month_table.setSortingEnabled(__sortingEnabled)
        self.third_month_table.verticalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Jack", None, QtGui.QApplication.UnicodeUTF8))
        self.third_month_table.verticalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Jane", None, QtGui.QApplication.UnicodeUTF8))
        self.third_month_table.verticalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "Joe", None, QtGui.QApplication.UnicodeUTF8))
        self.third_month_table.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.third_month_table.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.third_month_table.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.third_month_table.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.third_month_table.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.third_month_table.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("MainWindow", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.third_month_table.horizontalHeaderItem(6).setText(QtGui.QApplication.translate("MainWindow", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.third_month_table.horizontalHeaderItem(7).setText(QtGui.QApplication.translate("MainWindow", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.third_month_table.horizontalHeaderItem(8).setText(QtGui.QApplication.translate("MainWindow", "9", None, QtGui.QApplication.UnicodeUTF8))
        self.third_month_table.horizontalHeaderItem(9).setText(QtGui.QApplication.translate("MainWindow", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.third_month_table.horizontalHeaderItem(10).setText(QtGui.QApplication.translate("MainWindow", "11", None, QtGui.QApplication.UnicodeUTF8))
        self.third_month_table.horizontalHeaderItem(11).setText(QtGui.QApplication.translate("MainWindow", "12", None, QtGui.QApplication.UnicodeUTF8))
        self.third_month_table.horizontalHeaderItem(12).setText(QtGui.QApplication.translate("MainWindow", "13", None, QtGui.QApplication.UnicodeUTF8))
        self.third_month_table.horizontalHeaderItem(13).setText(QtGui.QApplication.translate("MainWindow", "14", None, QtGui.QApplication.UnicodeUTF8))
        self.third_month_table.horizontalHeaderItem(14).setText(QtGui.QApplication.translate("MainWindow", "15", None, QtGui.QApplication.UnicodeUTF8))
        self.third_month_table.horizontalHeaderItem(15).setText(QtGui.QApplication.translate("MainWindow", "16", None, QtGui.QApplication.UnicodeUTF8))
        self.third_month_table.horizontalHeaderItem(16).setText(QtGui.QApplication.translate("MainWindow", "17", None, QtGui.QApplication.UnicodeUTF8))
        self.third_month_table.horizontalHeaderItem(17).setText(QtGui.QApplication.translate("MainWindow", "18", None, QtGui.QApplication.UnicodeUTF8))
        self.third_month_table.horizontalHeaderItem(18).setText(QtGui.QApplication.translate("MainWindow", "19", None, QtGui.QApplication.UnicodeUTF8))
        self.third_month_table.horizontalHeaderItem(19).setText(QtGui.QApplication.translate("MainWindow", "20", None, QtGui.QApplication.UnicodeUTF8))
        self.third_month_table.horizontalHeaderItem(20).setText(QtGui.QApplication.translate("MainWindow", "21", None, QtGui.QApplication.UnicodeUTF8))
        self.third_month_table.horizontalHeaderItem(21).setText(QtGui.QApplication.translate("MainWindow", "22", None, QtGui.QApplication.UnicodeUTF8))
        self.third_month_table.horizontalHeaderItem(22).setText(QtGui.QApplication.translate("MainWindow", "23", None, QtGui.QApplication.UnicodeUTF8))
        self.third_month_table.horizontalHeaderItem(23).setText(QtGui.QApplication.translate("MainWindow", "24", None, QtGui.QApplication.UnicodeUTF8))
        self.third_month_table.horizontalHeaderItem(24).setText(QtGui.QApplication.translate("MainWindow", "25", None, QtGui.QApplication.UnicodeUTF8))
        self.third_month_table.horizontalHeaderItem(25).setText(QtGui.QApplication.translate("MainWindow", "26", None, QtGui.QApplication.UnicodeUTF8))
        self.third_month_table.horizontalHeaderItem(26).setText(QtGui.QApplication.translate("MainWindow", "27", None, QtGui.QApplication.UnicodeUTF8))
        self.third_month_table.horizontalHeaderItem(27).setText(QtGui.QApplication.translate("MainWindow", "28", None, QtGui.QApplication.UnicodeUTF8))
        self.third_month_table.horizontalHeaderItem(28).setText(QtGui.QApplication.translate("MainWindow", "29", None, QtGui.QApplication.UnicodeUTF8))
        self.third_month_table.horizontalHeaderItem(29).setText(QtGui.QApplication.translate("MainWindow", "30", None, QtGui.QApplication.UnicodeUTF8))
        self.third_month_table.horizontalHeaderItem(30).setText(QtGui.QApplication.translate("MainWindow", "31", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.third_month_table.isSortingEnabled()
        self.third_month_table.setSortingEnabled(False)
        self.third_month_table.setSortingEnabled(__sortingEnabled)
        self.fileMenu.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.helpMenu.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad.setText(QtGui.QApplication.translate("MainWindow", "Load", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHelp.setText(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExport.setText(QtGui.QApplication.translate("MainWindow", "Export...", None, QtGui.QApplication.UnicodeUTF8))

